### ISSUE TITLE
插件未实现 ocr 方法

### ISSUE THREAD

**Issue by Muyky** [wakewon/bob-plugin-simpletex#2]
按照readme 操作,密钥也已获取，但使用bob 截图翻译时，提示插件未实现 ocr 方法。无法使用
bob 版本：1.11.1[191]
<img width="436" alt="图片" src="https://github.com/user-attachments/assets/486879d0-bcdb-4b1f-a3cf-e34c01c45ad9">

**Comment by ProudBenzene** [comment]
遇到相同问题

**Comment by wakewon** [comment]
我这里未能复现，能否麻烦确认一下注册的时候是否是在`应用列表`里创建的应用并获取的ID？

另外，我在原教程评论看到说：
> 近期检测到一些恶意用户批量注册刷取免费API调用量，为了防止这一现象发生，现新注册开放平台时需要预先充值$5美金以上的金额进入您的账户。感谢您的理解与支持。

不知道出错的账号是否是新注册，且遇到了类似的提示？

**Comment by ProudBenzene** [comment]
您提到的账号限制应该仅限新注册用户，老用户不会有这个问题，我之前的其他API也都还可以用。

我在这里重新申请了一个App id 但是使用新id后也还是如此。

附上我的Bob设置图、SimpleTex截面图：

<img width="1246" alt="f751564280641c672f1b09a6cd70a66b" src="https://github.com/user-attachments/assets/40d04b9c-08f2-4c67-bd15-490a4862cec8">

<img width="961" alt="4fac742361ae1011d63238dc49557413" src="https://github.com/user-attachments/assets/f5a8ac84-aa95-46ed-b1d2-1538797f96c1">

**Comment by wakewon** [comment]
似乎是高版本一点的系统会遇到的问题，修了一下可以试试看v0.0.3新版本。
